version: "2.2"

networks:
  default:
  proxy:
    external:
      name: ${PROXY:-proxy}

volumes:
  whd-local-site-database:
  whd-local-site-public:
  whd-local-site-private:

services:
  memcache:
    image: public.ecr.aws/unocha/memcache:1.6
    hostname: whd-local-memcache
    container_name: whd-local-memcache
    environment:
      MEMCACHE_MAX_MEMORY: 64
    ports:
      - "11211"
    networks:
      - default

  mysql:
    image: public.ecr.aws/unocha/mysql:10.6
    hostname: whd-local-mysql
    container_name: whd-local-mysql
    environment:
      - MYSQL_DB=whd
      - MYSQL_USER=whd
      - MYSQL_PASS=whd
    volumes:
      - "whd-local-site-database:/var/lib/mysql:rw"
    networks:
      - default

  drupal:
    image: public.ecr.aws/unocha/whd-2023-site:local
    hostname: whd-local-site
    container_name: whd-local-site
    depends_on:
      - memcache
      - mysql
    volumes:
      - "./shared/settings:/srv/www/shared/settings:ro"
      # Mount the composer files and patches.
      - "../composer.json:/srv/www/composer.json:rw"
      - "../composer.patches.json:/srv/www/composer.patches.json:rw"
      - "../composer.lock:/srv/www/composer.lock:rw"
      - "../PATCHES:/srv/www/PATCHES:rw"
      # Mount directory for database.
      - "../database:/srv/www/database:rw"
      # Mount volumes for the private and public files.
      - "whd-local-site-public:/srv/www/html/sites/default/files:rw"
      - "whd-local-site-private:/srv/www/html/sites/default/private:rw"
      # Mount the folders needed for the tests.
      - "../phpcs.xml:/srv/www/phpcs.xml:ro"
      - "../phpunit.xml:/srv/www/phpunit.xml:ro"
      # Mount local custom code.
      - "../html/modules/custom:/srv/www/html/modules/custom:rw"
      - "../html/themes/custom:/srv/www/html/themes/custom:rw"
      # Mount configuration and allow overriding it.
      - "../config:/srv/www/config:rw"
      - "../config_dev:/srv/www/config_dev:rw"
    environment:
      - TERM=xterm
      - ENVIRONMENT=dev
      - NGINX_SERVERNAME=whd-local.test
      - NGINX_OVERRIDE_PROTOCOL=HTTP,whd-local.test
      - DRUSH_OPTIONS_URI=https://whd-local.test
      - DRUPAL_DB_DATABASE=whd
      - DRUPAL_DB_USERNAME=whd
      - DRUPAL_DB_PASSWORD=whd
      - DRUPAL_DB_HOST=mysql
      - DRUPAL_DB_DRIVER=mysql
      - PHP_ENVIRONMENT=dev
      - PHP_XDEBUG=true
      # Rate limiting.
      - NGINX_LIMIT_HUMANS=1024r/s
      - NGINX_BURST_HUMANS=1024
      # Local proxy.
      - VIRTUAL_HOST=whd-local.test
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=${PROXY:-proxy}
      - HTTPS_METHOD=noredirect
    labels:
      caddy: whd-local.test
      caddy.reverse_proxy: "{{upstreams}}"
    networks:
      - default
      - proxy
