label: 最新评论
description: 最新评论。
display:
  default:
    display_title: 默认
    display_options:
      title: 最新评论
      fields:
        changed:
          settings:
            past_format: '@interval 前'
      empty:
        area_text_custom:
          content: 没有评论。
  block_1:
    display_title: 区块
    display_options:
      block_description: 最新评论
      block_category: 列表（视图）
