label: Commentaires
description: 'Trouver et gérer les commentaires.'
display:
  default:
    display_title: 'Par défaut'
    display_options:
      title: Commentaires
      fields:
        subject:
          label: Objet
        name:
          label: Auteur
        entity_id:
          label: 'Posté sur'
        changed:
          label: 'Mis à jour'
        operations:
          label: Actions
      pager:
        options:
          tags:
            next: "suivant\_›"
            previous: "‹\_précédent"
            first: "«\_premier"
            last: "dernier\_»"
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      empty:
        area_text_custom:
          content: 'Aucun commentaire disponible.'
      filters:
        subject:
          expose:
            label: Objet
        combine:
          expose:
            label: "Nom de l'auteur"
        langcode:
          expose:
            label: Langue
      use_more_text: plus
  page_published:
    display_title: 'Commentaires publiés'
    display_options:
      display_description: 'La liste des commentaires approuvés.'
      menu:
        title: Commentaires
        description: 'Commentaires publiés'
  page_unapproved:
    display_title: 'Commentaires non approuvés'
    display_options:
      fields:
        subject:
          label: Objet
        name:
          label: Auteur
        entity_id:
          label: 'Posté sur'
        changed:
          label: 'Mis à jour'
        operations:
          label: Actions
      filters:
        subject:
          expose:
            label: Objet
        combine:
          expose:
            label: "Nom de l'auteur"
        langcode:
          expose:
            label: Langue
      display_description: 'La liste des commentaires non-approuvés.'
      menu:
        title: 'Commentaires non approuvés'
        description: 'Commentaires non-approuvés'
