label: 'Commentaires récents'
description: 'Commentaires récents.'
display:
  default:
    display_title: 'Par défaut'
    display_options:
      title: 'Commentaires récents'
      fields:
        changed:
          settings:
            past_format: 'Il y a @interval'
  block_1:
    display_title: Bloc
    display_options:
      block_description: 'Commentaires récents'
      block_category: 'Listes (Views)'
