_core:
  default_config_hash: aDAuKinNUSmlWFFUTQRGt_8VoL0d8RUKNeYKlClzscw
client_id: HID_CLIENT_ID_DO_NOT_COMMIT_TO_REPOSITORY
client_secret: HID_CLIENT_SECRET_DO_NOT_COMMIT_TO_REPOSITORY
base_url: 'https://auth.humanitarian.id'
auto_redirect: false
disable_default: false
disable_password_fields: true
disable_email_field: true
disable_user_field: true
disable_user_create: true
maintenance_access: false
